### ISSUE TITLE
Unable to get the inventory host file

### ISSUE THREAD

**Issue by richiesgr** [doitian/aliyun-ansible-inventory#3]
Hi
I'm trying to integrate your script with ansible tower and it's not working
when I run 
`ansible all -i inventory --list-hosts`

I get a list of hostname as expected
hosts (9):
    Confluent
    Viper
    Exchange
    mysqldb
    memcached
    Zookeeper
    imply-db
    Ansible_control

But when I run the playbook to generate the host file I get an error

> fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: u\"hostvars['groups.ecs']\" is undefined\n\nThe error appears to have been in '/root/aliyun-ansible-inventory/hosts.yml': line 7, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n      command: cp /etc/hosts hosts\n    - name: Update ecs IPs in hosts file\n      ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: u\"hostvars['groups.ecs']\" is undefined"}

So I understand that the hosts file is not updated so ansible is unable to find the group.ecs ?
Could you help me 
Thanks

**Comment by doitian** [comment]
It looks like your account has no ecs hosts. You can still use the inventory, but the example `hosts.yml` use `groups.ecs` to get a list of ecs hosts, that's why the command failed.

Try to run `inventory/aliyun.py` directly, it should list of the found instances. Or `inventory/aliyun.py --refresh-cache` to refresh cache. You can also open the configured cache file, it is just a YAML file.

**Comment by richiesgr** [comment]
Hi doitian
I've hosts in ecs but what is group.ecs ?
is group.ecs need to be in the tag of the machine or somewhere else ?

yes the inventory/aliyun.py works but I want to use it in ansible tower as script and it need to be formatted as JSON file
Your script do that ?

Thanks

**Comment by doitian** [comment]
It is a generated group which contains all ecs hosts.

Have you tried [import the inventory script via SCM](http://docs.ansible.com/ansible-tower/latest/html/administration/scm-inv-source.html)?

You can either paste `inventory/aliyun.py` as [Custom Inventory Script](http://docs.ansible.com/ansible-tower/latest/html/administration/custom_inventory_script.html)。You many need to update `read_settings` function to initialize you settings, since the ini file is not available.

**Comment by doitian** [comment]
Staled
